import os

# CONSTANTS WHICH DEFINES WHAT FILE NAMES AND WHICH PATH EVERYTHING
# IS STORED

# DO NOT MODIFY!
ROOT_DIR = os.path.dirname(os.path.realpath(__file__))
ASSET_FOLDER = 'asset'
ASSET_DIR = f'{ROOT_DIR}/{ASSET_FOLDER}'
ACTIVITY_FOLDER = 'storeroom'
ACTIVITY_DIR = f'{ROOT_DIR}/{ACTIVITY_FOLDER}'
DATA_FILE = 'data.dat'